<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Aspirasi;

class AspirasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Budi Santoso',
                'address' => 'Jl. Gajah Raya, Kota Semarang',
                'phone' => '0821349105769',
                'tujuan' => 'Perbaikan Jalan',
                'message' => 'Perbaikan jalan rusak di lingkungan warga',
                'nama_dewan' => 'Dinda Ari Ayu Isnani, S.T',
                'dapil' => 'Dapil 2 (Gayamsari, Genuk, Pedurungan)',
                'urgensi' => 4,
                'cakupan_wilayah' => 4,
                'dampak_sosial' => 2,
                'kategori' => 1,
                'status' => 'Sedang Diproses',
            ],
            [
                'name' => 'Siti Marwati',
                'address' => 'Jl. Kartini, Semarang Tengah',
                'phone' => '082139876234',
                'tujuan' => 'Perbaikan Trotoar',
                'message' => 'Trotoar rusak membahayakan pejalan kaki',
                'nama_dewan' => 'Arya Setya Novanto, S.H., M.H',
                'dapil' => 'Dapil 1 (Semarang Tengah, Semarang Timur, Semarang Utara)',
                'urgensi' => 3,
                'cakupan_wilayah' => 3,
                'dampak_sosial' => 3,
                'kategori' => 1,
                'status' => 'Belum Ditinjau',
            ],
            [
                'name' => 'Rina Kusuma',
                'address' => 'Jl. Wolter Monginsidi, Genuk',
                'phone' => '082153214567',
                'tujuan' => 'Pengadaan Posyandu',
                'message' => 'Posyandu dibutuhkan pelayanan balita warga',
                'nama_dewan' => 'Nunung Sriyanto, S.H., M.M',
                'dapil' => 'Dapil 2 (Gayamsari, Genuk, Pedurungan)',
                'urgensi' => 5,
                'cakupan_wilayah' => 2,
                'dampak_sosial' => 4,
                'kategori' => 2,
                'status' => 'Sedang Diproses',
            ],
            [
                'name' => 'Agus Pranoto',
                'address' => 'Jl. Tirto Agung, Tembalang',
                'phone' => '082145672334',
                'tujuan' => 'Renovasi Sekolah',
                'message' => 'Gedung sekolah rusak butuh renovasi',
                'nama_dewan' => 'Herlambang Prabowo, S.A',
                'dapil' => 'Dapil 3 (Candisari, Tembalang)',
                'urgensi' => 4,
                'cakupan_wilayah' => 3,
                'dampak_sosial' => 3,
                'kategori' => 3,
                'status' => 'Selesai',
            ],
            [
                'name' => 'Dewi Rahma',
                'address' => 'Jl. Sukun Raya, Banyumanik',
                'phone' => '082176541234',
                'tujuan' => 'Pelatihan UMKM',
                'message' => 'Pelatihan UMKM sangat dibutuhkan warga',
                'nama_dewan' => 'Dyah Tunjung Pudyawati, S.M.B., M.M',
                'dapil' => 'Dapil 4 (Banyumanik, Gajahmungkur, Gunungpati)',
                'urgensi' => 3,
                'cakupan_wilayah' => 4,
                'dampak_sosial' => 4,
                'kategori' => 4,
                'status' => 'Sedang Diproses',
            ],
            [
                'name' => 'Eko Haryanto',
                'address' => 'Jl. Gondoriyo, Ngaliyan',
                'phone' => '082112345789',
                'tujuan' => 'Pembuatan Taman',
                'message' => 'Taman hijau diperlukan untuk bermain warga',
                'nama_dewan' => 'H. Mualim, S.Pd., M.H., M.M',
                'dapil' => 'Dapil 5 (Mijen, Ngaliyan, Tugu)',
                'urgensi' => 2,
                'cakupan_wilayah' => 2,
                'dampak_sosial' => 3,
                'kategori' => 5,
                'status' => 'Belum Ditinjau',
            ],
            [
                'name' => 'Fitriani Ningsih',
                'address' => 'Jl. Cendrawasih, Semarang Selatan',
                'phone' => '082198765321',
                'tujuan' => 'Peningkatan Drainase',
                'message' => 'Drainase buruk menyebabkan banjir tahunan',
                'nama_dewan' => 'Drs. H. Abdul Majid',
                'dapil' => 'Dapil 6 (Semarang Barat, Semarang Selatan)',
                'urgensi' => 5,
                'cakupan_wilayah' => 3,
                'dampak_sosial' => 4,
                'kategori' => 1,
                'status' => 'Selesai',
            ],
            [
                'name' => 'Raka Putra',
                'address' => 'Jl. Puspowarno, Semarang Barat',
                'phone' => '082135461109',
                'tujuan' => 'Penambahan Penerangan Jalan',
                'message' => 'Butuh lampu jalan di sekitar lingkungan warga',
                'nama_dewan' => 'Drs. H. Abdul Majid',
                'dapil' => 'Dapil 6 (Semarang Barat, Semarang Selatan)',
                'urgensi' => 3,
                'cakupan_wilayah' => 2,
                'dampak_sosial' => 3,
                'kategori' => 1,
                'status' => 'Belum Ditinjau',
            ],
            [
                'name' => 'Wulan Anggraini',
                'address' => 'Jl. Dr. Cipto, Semarang Timur',
                'phone' => '082199874563',
                'tujuan' => 'Pemeriksaan Rutin Posyandu',
                'message' => 'Perlu posyandu aktif untuk kesehatan balita',
                'nama_dewan' => 'Arya Setya Novanto, S.H., M.H',
                'dapil' => 'Dapil 1 (Semarang Tengah, Semarang Timur, Semarang Utara)',
                'urgensi' => 2,
                'cakupan_wilayah' => 3,
                'dampak_sosial' => 3,
                'kategori' => 2,
                'status' => 'Selesai',
            ],
            [
                'name' => 'Fikri Ramadhan',
                'address' => 'Jl. Banjarsari Selatan, Pedurungan',
                'phone' => '082145768909',
                'tujuan' => 'Bantuan Usaha Mikro',
                'message' => 'Pelaku UMKM butuh bantuan alat produksi baru',
                'nama_dewan' => 'Nunung Sriyanto, S.H., M.M',
                'dapil' => 'Dapil 2 (Gayamsari, Genuk, Pedurungan)',
                'urgensi' => 4,
                'cakupan_wilayah' => 4,
                'dampak_sosial' => 4,
                'kategori' => 4,
                'status' => 'Sedang Diproses',
            ],
            [
                'name' => 'Intan Permata',
                'address' => 'Jl. Kawi, Gajahmungkur',
                'phone' => '082167398765',
                'tujuan' => 'Pelatihan Komputer Gratis',
                'message' => 'Perlu pelatihan komputer bagi remaja dan dewasa',
                'nama_dewan' => 'Dyah Tunjung Pudyawati, S.M.B., M.M',
                'dapil' => 'Dapil 4 (Banyumanik, Gajahmungkur, Gunungpati)',
                'urgensi' => 3,
                'cakupan_wilayah' => 3,
                'dampak_sosial' => 3,
                'kategori' => 3,
                'status' => 'Sedang Diproses',
            ],
            [
                'name' => 'Galih Setiawan',
                'address' => 'Jl. Taman Mijen Indah, Mijen',
                'phone' => '082123654789',
                'tujuan' => 'Pengelolaan Sampah Terpadu',
                'message' => 'Diperlukan TPS terdekat untuk pengelolaan sampah',
                'nama_dewan' => 'H. Mualim, S.Pd., M.H., M.M',
                'dapil' => 'Dapil 5 (Mijen, Ngaliyan, Tugu)',
                'urgensi' => 4,
                'cakupan_wilayah' => 4,
                'dampak_sosial' => 4,
                'kategori' => 5,
                'status' => 'Belum Ditinjau',
            ],
            [
                'name' => 'Larasati Dewi',
                'address' => 'Jl. Tlogosari Raya, Pedurungan',
                'phone' => '082134567901',
                'tujuan' => 'Pengecoran Jalan Gang',
                'message' => 'Akses gang sempit perlu pengecoran segera',
                'nama_dewan' => 'Dinda Ari Ayu Isnani, S.T',
                'dapil' => 'Dapil 2 (Gayamsari, Genuk, Pedurungan)',
                'urgensi' => 3,
                'cakupan_wilayah' => 2,
                'dampak_sosial' => 2,
                'kategori' => 1,
                'status' => 'Selesai',
            ],
            [
                'name' => 'Reza Maulana',
                'address' => 'Jl. Sultan Agung, Semarang Selatan',
                'phone' => '082176543890',
                'tujuan' => 'Perbaikan Saluran Air',
                'message' => 'Saluran air mampet menyebabkan banjir kecil',
                'nama_dewan' => 'Drs. H. Abdul Majid',
                'dapil' => 'Dapil 6 (Semarang Barat, Semarang Selatan)',
                'urgensi' => 4,
                'cakupan_wilayah' => 4,
                'dampak_sosial' => 3,
                'kategori' => 1,
                'status' => 'Sedang Diproses',
            ],
            [
                'name' => 'Vina Lestari',
                'address' => 'Jl. Palir Raya, Ngaliyan',
                'phone' => '082112345666',
                'tujuan' => 'Pembuatan Taman Lingkungan',
                'message' => 'Warga butuh taman kecil untuk tempat bermain',
                'nama_dewan' => 'H. Mualim, S.Pd., M.H., M.M',
                'dapil' => 'Dapil 5 (Mijen, Ngaliyan, Tugu)',
                'urgensi' => 3,
                'cakupan_wilayah' => 2,
                'dampak_sosial' => 3,
                'kategori' => 5,
                'status' => 'Belum Ditinjau',
            ],
            [
                'name' => 'Budi Hartono',
                'address' => 'Jl. Imam Bonjol, Semarang Tengah',
                'phone' => '082199003456',
                'tujuan' => 'Pemeliharaan Gedung Sekolah',
                'message' => 'Kondisi sekolah dasar perlu perbaikan cepat',
                'nama_dewan' => 'Arya Setya Novanto, S.H., M.H',
                'dapil' => 'Dapil 1 (Semarang Tengah, Semarang Timur, Semarang Utara)',
                'urgensi' => 5,
                'cakupan_wilayah' => 3,
                'dampak_sosial' => 4,
                'kategori' => 3,
                'status' => 'Sedang Diproses',
            ],
            [
                'name' => 'Dimas Saputra',
                'address' => 'Jl. Ngesrep Barat, Banyumanik',
                'phone' => '082155443321',
                'tujuan' => 'Pembangunan Poskamling',
                'message' => 'Perlu poskamling untuk keamanan lingkungan RT',
                'nama_dewan' => 'Dyah Tunjung Pudyawati, S.M.B., M.M',
                'dapil' => 'Dapil 4 (Banyumanik, Gajahmungkur, Gunungpati)',
                'urgensi' => 3,
                'cakupan_wilayah' => 2,
                'dampak_sosial' => 3,
                'kategori' => 1,
                'status' => 'Belum Ditinjau',
            ],
            [
                'name' => 'Nadia Ayuningtyas',
                'address' => 'Jl. Arteri Soekarno Hatta, Genuk',
                'phone' => '082199876543',
                'tujuan' => 'Pengadaan Ambulans Gratis',
                'message' => 'Masyarakat butuh ambulans gratis untuk warga',
                'nama_dewan' => 'Nunung Sriyanto, S.H., M.M',
                'dapil' => 'Dapil 2 (Gayamsari, Genuk, Pedurungan)',
                'urgensi' => 5,
                'cakupan_wilayah' => 5,
                'dampak_sosial' => 5,
                'kategori' => 2,
                'status' => 'Sedang Diproses',
            ],
        ];

        foreach ($data as $item) {
            Aspirasi::create($item);
        }
    }
}
